### ISSUE TITLE
App crashes on calling  notifyExpandableDataSetChanged(); for a new Item when added

### ISSUE THREAD

**Issue by shrinijaiswal** [chriselder/expandable-recycler-view#2]
Please help , I am unable to fix the issue past 5 days and in lot of pressure . Please any and all help highly appreciated .

**Comment by chriselderxyz** [comment]
@shrinijaiswal, I'll likely need a bit more information to look into that issue.

Although this repo hasn't been maintained for about 2 years

May be more sustainable to look into https://github.com/thoughtbot/expandable-recycler-view for similar functionality, or https://github.com/lisawray/groupie as well.
